package usf.java.sqlreflect;

public interface SqlConstants {

	String DATABASE_NAME = "DATABASE_NAME";
	
	String TABLE_NAME  = "TABLE_NAME";
	String TABLE_TYPE  = "TABLE_TYPE";
	
	String PK_NAME = "PK_NAME";
	String KEY_SEQ = "KEY_SEQ";
	
	String PROCEDURE_NAME  = "PROCEDURE_NAME";
	String PROCEDURE_TYPE  = "PROCEDURE_TYPE";
	
	String FUNCTION_NAME  = "FUNCTION_NAME";
	String FUNCTION_TYPE  = "FUNCTION_TYPE";
	
	String COLUMN_NAME  = "COLUMN_NAME";
	String COLUMN_TYPE  = "COLUMN_TYPE";
	String COLUMN_SIZE  = "COLUMN_SIZE";
	String COLUMN_CLASS = "COLUMN_CLASS"; 
	
	String DATA_TYPE = "DATA_TYPE";
	String TYPE_NAME = "TYPE_NAME";
	String LENGTH = "LENGTH";

	String[] DATABASE_COLUMNS  	= {};
	String[] TABLE_COLUMNS  	= {TABLE_NAME, TABLE_TYPE};
	String[] COLUMNS_COLUMNS  	= {TABLE_NAME, COLUMN_NAME, DATA_TYPE, TYPE_NAME, COLUMN_SIZE};
	String[] PRIMARY_KEY_COLUMNS= {};
	String[] PROCEDURE_COLUMNS  = {PROCEDURE_NAME, PROCEDURE_TYPE};
	String[] ARGUMENT_COLUMNS  	= {PROCEDURE_NAME, COLUMN_NAME, COLUMN_TYPE, DATA_TYPE, TYPE_NAME, LENGTH};
	String[] FUNCTION_COLUMNS  	= {FUNCTION_NAME, FUNCTION_TYPE};
	
}