package usf.java.sqlreflect;

public interface SqlConstants {
	
	String DATA_TYPE = "DATA_TYPE";
	String TYPE_NAME = "TYPE_NAME";
	String LENGTH = "LENGTH";
	
	String PK_NAME = "PK_NAME";
	String KEY_SEQ = "KEY_SEQ";

	String COLUMN_CLASS = "COLUMN_CLASS"; 
	String COLUMN_NAME  = "COLUMN_NAME";
	String COLUMN_TYPE  = "COLUMN_TYPE";
	String COLUMN_SIZE  = "COLUMN_SIZE";
	
	String TABLE_SCHEM = "TABLE_SCHEM";
	String TABLE_NAME  = "TABLE_NAME";
	String TABLE_TYPE  = "TABLE_TYPE";
	
	String PROCEDURE_SCHEM = "PROCEDURE_SCHEM";
	String PROCEDURE_NAME  = "PROCEDURE_NAME";
	String PROCEDURE_TYPE  = "PROCEDURE_TYPE";
	
	String FUNCTION_SCHEM = "FUNCTION_SCHEM";
	String FUNCTION_NAME  = "FUNCTION_NAME";
	String FUNCTION_TYPE  = "FUNCTION_TYPE";

}